### ISSUE TITLE
Use std::array over c style arrays

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#10]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/src/turtle_mover.cpp#L327

Bad memory access calls produce segmentation faults on linux and can completely crash some windows systems. C style arrays are a common culprit for bugs like these. std::array is a container similar to std::vector with protected access functions that will throw descriptive errors when bad access calls are made.

Ex: 
```
std::array<int,5> myarray;
myarray.at(3) = 42; // Always use .at instead of [ ] to reference array contents because [ ] does not do bounds checking. 

```

**Comment by cokumura2019** [comment]
Makes sense!
