### ISSUE TITLE
Only use ros printing macros in ros nodes.

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#11]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/src/turtle_mover.cpp#L394

Calls that push directly to the screen will pollute logs files and make them grow unnecessarily large. Using the ROS print macros will force the system to only log important data.

**Comment by cokumura2019** [comment]
Resolved
