### ISSUE TITLE
Always give descriptive and meaningful names.

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#13]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/srv/circle.srv#L1

Never use single letter variable names. This was done in the early 90s to save on disc space and the practice has continued even though it makes code more difficult to read. The more your code reads like the english language, the better.

Be sure to take full advantage of the autocomplete feature in your IDE for longer variable names.

**Comment by airfield20** [comment]
r should be radius and response should be  success.

**Comment by cokumura2019** [comment]
Great points!
