### ISSUE TITLE
Always give nodes descriptive default names.

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#3]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver_ui/scripts/turtle_controller.py#L38

**Comment by airfield20** [comment]
This name will not always be remapped, especially when being run from the command line.

**Comment by cokumura2019** [comment]
That's true that there may be some opportunities where I might want to start a ROS Node using rosrun on the CLI rather than a launch file. In that case, the node's name would be i_will_be_remapped which is clearly not ideal
