### ISSUE TITLE
Switch to object oriented design scheme

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#4]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver_ui/scripts/turtle_controller.py#L50

Your implementation logic in this project looks great. Next, lets refactor your code to use an object oriented design scheme. This website has a good tutorial for python:

https://roboticsbackend.com/oop-with-ros-in-python/

**Comment by cokumura2019** [comment]
Done - abstracted each of the drive functions to their own class and initalized all of them into an array in main. This allows for a list to store the references to each of the function "sub-services" and utilizes a generic function to invoke them when a message is received from the user input
