### ISSUE TITLE
Dont use raw pointers

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#7]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/src/turtle_mover.cpp#L28

Raw pointers have the potential to be mismanaged and cause memory leaks or segmentation faults. You might have thoroughly checked your implementation to make sure there are none, but the next person who edits your code may not be as thorough.

For this reason, we always prefer to use the c++ standard implementation of smart pointers shared_ptr and unique_ptr. Ros has some boost based implementations themselves that predate the official c++ release, but prefer the c++ implementation over the boost implementation where possible.

**Comment by cokumura2019** [comment]
Great point! I think I can also improve the structure of the C++ program by requiring the functions to take in the respective nodehandle's pointer. I think this would be great for decoupling

**Comment by cokumura2019** [comment]
Great advice for pointers in general and avoiding memory leaks automatically
