### ISSUE TITLE
Switch to OO architecture.

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#8]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/src/turtle_mover.cpp#L116

Same as last comment. Reference this for c++: https://roboticsbackend.com/oop-with-ros-in-cpp/

**Comment by cokumura2019** [comment]
Done! Would appreciate another look on my commit that has the C++ OOP commit - I wonder if my approach was optimal?
