### ISSUE TITLE
Prefer while loops over do while loops for code readability.

### ISSUE THREAD

**Issue by airfield20** [cokumura2019/turtle_sim#9]
https://github.com/cokumura2019/turtle_sim/blob/c2da5f0416a45f9db9e466aabe3a5d6cabee130c/src/turtle_driver/src/turtle_mover.cpp#L306

Do while loops have a specfic use case and shouldnt be used unless the situation specifically calls for it instead of a while loop. This is usually done for code readability.

Only use do while loops when you want to reduce code duplication.

**Comment by cokumura2019** [comment]
Removed all unnecessary do while() loops
